### ISSUE TITLE
How to view Login and logout status of User (student)?

### ISSUE THREAD

**Issue by truonglx1** [openedx-unsupported/edx-documentation#1047]
I've just installed & run openedx  successfull, it's still runing now.
I've a small trouble in how to check user login & time of login for each users (like students), time per day...

Thanks for support!.

**Comment by truonglx1** [comment]
any help for my problem...

Thanks alot.

**Comment by lamagnifica** [comment]
Hi @truonglx1 apologies, we don't typically check the issues list in this repo.
There are a number of ways to ask questions and get answers from the community including mailing lists and slack channels. The best place to get started is by setting up a user account on our Open edX portal web site, and investigating the resources on this page: https://open.edx.org/resources/community-discussions.
I hope you'll find the answers you need from the Open edX community.
