### ISSUE TITLE
Edx courses broken link 

### ISSUE THREAD

**Issue by Adamalshihabi** [openedx-unsupported/edx-documentation#1586]
https://courses.edx.org/courses/course-v1:W3Cx+HTML5.1x+1T2017/courseware/b246c15d3a1044ccb4564ea22fbc4821/ef075a883df1447698d557fe6f6222d0/?child=first
  
the link under the name :  **Google Code: Web Authoring Statistics: Classes.** 

the page not found[https://developers.google.com/webmasters/state-of-the-web/2005/classes?csw=1](url)

**Comment by grantgoodmanedX** [comment]
This is a course issue, not an edX documentation issue. You could possibly bring it to the attention of the course staff in the course's discussion forums.
