### ISSUE TITLE
"Extending the edX Platform" doc is very out of date

### ISSUE THREAD

**Issue by rgraber** [openedx-unsupported/edx-documentation#2114]
https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/extending_platform/index.html hasn't been updated since 2014 and contains lots of out-of-date information. It is also missing any information about plugins, MFEs, etc. that have been developed since.

**Comment by feanil** [comment]
@rgraber thanks for taking this on, any chance I could get you to make the new page in the new docs site instead and just replace the old page with a forwarding link?  It sounds like what you're going to write would probably go under here: https://docs.openedx.org/en/latest/developers/concepts/index.html

**Comment by feanil** [comment]
Or maybe a series of how-tos?

**Comment by rgraber** [comment]
Oh, didn't realize this page was effectively deprecated. Is this entire repo supposed to be deprecated soon?

**Comment by rgraber** [comment]
I actually didn't realize we already had a better version of this information. Is the plan to deprecate edx-documentation overall eventually?
ps @robrap , who first pointed me at this

**Comment by rgraber** [comment]
Asking because if we're deprecating the repo entirely this ticket is redundant and I can make a new one to update https://docs.openedx.org/en/latest/developers/concepts/index.html, although that one is pretty up to date. The ticket would be more just to include the things discussed here: https://github.com/openedx/edx-platform/issues/31659

**Comment by feanil** [comment]
The plan is to eventually deprecate and remove the entire developer guide and move it to the new space.  I think as an interim step, it would be good to cross link the new content from this old page but having it in the new repo will reduce future work to move it there.  Let me know if that's not clear.

**Comment by rgraber** [comment]
That makes sense to me. I'll close this ticket, make a new one in docs.openedx.org, and add a task in that ticket to change this old page to point to the new one.
