### ISSUE TITLE
Issue on page /set_up_course/studio_add_course_information/creating_new_course.html

### ISSUE THREAD

**Issue by MAATALLAAMINE3177** [openedx-unsupported/edx-documentation#2270]
[الأدب العالمي مفاهيم ومصطلحات.pdf](https://github.com/user-attachments/files/16019574/default.pdf)
Your issue content here.

**Comment by MAATALLAAMINE3177** [comment]
[](https://drive.google.com/file/d/1VR1MfnlEWNKaTmKvgiXg4rqQHHr7BJXl/view?usp=drive_link)

**Comment by feanil** [comment]
I'm not sure how this is related to that page or what changes need to be made to that page.  If you have more information please feel free to re-open the issue with those details.
