### ISSUE TITLE
Change Log & Version

### ISSUE THREAD

**Issue by yarko** [openedx-unsupported/edx-documentation#25]
I just noticed the change log included November change at the top of October list, FYI:

http://edx-open-learning-xml.readthedocs.org/en/latest/change_log.html

I would have linked to something other than "latest" - if there were a tag to link to! --- so maybe that's a second issue...

**Comment by mhoeber** [comment]
Hi @yarko, I've got an open pull request that resolves the change log issue, thanks.

Currently we are only using "latest" in doc, and that reflects what's in master.  That will be changing soon as we have versions for named releases of Open edX.  

Thanks
Mark
