### ISSUE TITLE
Bad link

### ISSUE THREAD

**Issue by pmitros** [openedx-unsupported/edx-documentation#756]
http://edx.readthedocs.org/projects/devdata/en/latest/glossary.html#c (for content experiment) points to http://edx.readthedocs.org/projects/edx-partner-course-staff/en/latest/content_experiments/index.html which is a bad link.

Aside from that, it really ought to have a pointer to: 
http://edx.readthedocs.org/projects/devdata/en/latest/internal_data_formats/sql_schema.html#columns-in-the-user-api-usercoursetag-table

A common question a researcher might ask is "How do I analyze randomized control trials?" That's not possible to figure out without reading through basically all the docs.

**Comment by lamagnifica** [comment]
Apologies for being so slow to respond to this issue, we really work from DOC stories in JIRA or pull requests and don't check for issues in GitHub.
The link is now correct, to 
http://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/course_features/content_experiments/content_experiments_overview.html#overview-of-content-experiments
The glossary is shared among several guides written for different audiences. We can certainly add a sentence about where to find information about how the data is stored. Could you open either a story or a PR with your recommended text? Thanks @pmitros
